### ISSUE TITLE
error file name

### ISSUE THREAD

**Issue by alchu4n** [osmedeus/osmedeus-workflow#1]
https://github.com/osmedeus/osmedeus-workflow/blob/main/general/screenshot.yaml
```yaml
- inputfile: "{{.Output}}/probing/diffhttp-{{.Workspace}}.txt"
```
in the probing finder no diffhttp-{{.Workspace}}.txt file

**Comment by j3ssie** [comment]
Thank you for pointing it out, I have already pushed a fix for it.
