### ISSUE TITLE
error file name

### ISSUE THREAD

**Issue by NAXG** [osmedeus/osmedeus-workflow#4]
<img width="625" alt="image" src="https://github.com/osmedeus/osmedeus-workflow/assets/28560949/579e4b40-8b27-4ca7-91fe-af0efd44e98b">

in the probing finder no diffhttp-{{.Workspace}}.txt file

**Comment by j3ssie** [comment]
Thank you for bringing this issue to our attention. We have addressed it, and it should be functioning properly now
