### ISSUE TITLE
unique-beautify-{{Workspace}}.txt does not exist

### ISSUE THREAD

**Issue by NAXG** [osmedeus/osmedeus-workflow#5]
<img width="801" alt="image" src="https://github.com/osmedeus/osmedeus-workflow/assets/28560949/54f153b3-31fa-4864-a971-a174d7968461">
<img width="756" alt="image" src="https://github.com/osmedeus/osmedeus-workflow/assets/28560949/7e697ea3-4f81-4212-bef1-019e79b56ac1">

**Comment by j3ssie** [comment]
Thank you for bringing this issue to our attention. It should be fixed now
